### ISSUE TITLE
Removed references to "gender" from the permissions table

### ISSUE THREAD

**Issue by jwalgran** [OpenTreeMap/OTM2#1945]
The ``treemap_fieldpermission`` table is used when generating a CSV export. Lingering references to the ``gender`` field are likely the source of this celery task failure:

```
^[[1;34m[2015-02-02 15:38:07,307: DEBUG/MainProcess] Task accepted: exporter.tasks.async_csv_export[7632ed65-ce5a-41ea-812a-7912794d877b] pid:1078^[[0m
^[[1;31m[2015-02-02 15:38:07,380: ERROR/MainProcess] Task exporter.tasks.async_csv_export[7632ed65-ce5a-41ea-812a-7912794d877b] raised unexpected: FieldError(u"Cannot resolve keyword u'gender' into field. Choices are: common_name, cultivar, fact_sheet_url, fall_conspicuous, flower_conspicuous, flowering_period, fruit_or_nut_period, genus, has_wildlife_value, id, instance, is_native, itreecodeoverride, max_diameter, max_height, other_part_of_name, otm_code, palatable_human, plant_guide_url, species, speciesimportrow, tree, udfs",)
Traceback (most recent call last):
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/otm/app/opentreemap/exporter/tasks.py", line 117, in async_csv_export
    .values(*ordered_fields)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/contrib/gis/db/models/query.py", line 23, in values
    return self._clone(klass=GeoValuesQuerySet, setup=True, _fields=fields)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 849, in _clone
    c._setup_query()
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 992, in _setup_query
    self.query.add_fields(self.field_names, True)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1528, in add_fields
    allow_explicit_fk=True, outer_if_first=True)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1351, in setup_joins
    names, opts, allow_many, allow_explicit_fk)
  File "/usr/local/otm/env/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1274, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))

**Comment by jwalgran** [comment]
Fixed by #1947
